tasks:
    - name: framework
      # change working directory as per configured in `checkoutLocation`
      # which is configured above as `/workspaces/framework`
      before: |
          cd ./framework
      init: |
          npm install
      command: |
         npm run dev
ports:
    - name: Demo UI
      port: 3000
      onOpen: open-preview
      visibility: private

