tasks:
    - name: framework
      # change working directory as per configured in `checkoutLocation`
      # which is configured above as `/workspaces/framework`
      before: |
          cd ./framework
      init: |
          echo npm install
      command: |
          echo npm run dev
