tasks:
    - name: framework
      # change working directory as per configured in `checkoutLocation`
      # which is configured above as `/workspaces/framework`
      before: |
          cd ./framework
      init: |
          npm install
      command: |
         npm run dev
ports:
    - name: Demo UI
      port: 3000
      onOpen: open-preview
      visibility: private
    - name: Metering API
      port: 3001
      visibility: private
    - name: Moleculer Lab
      port: 3210
      visibility: private
    - name: PWA
      port: 3002
      visibility: public
      onOpen: open-browser
