jobs:
  build:
    docker:
      - image: stromdao/eaf:latest
    working_directory: /app/circleci

    steps:
      - checkout

      # Add any steps needed for building your application inside the Docker container

  test:
    docker:
      - image: stromdao/eaf:latest
    working_directory: /app/circleci

    steps:
      - checkout

      - run:
          name: Wait for container to start
          command: sleep 15

      # Add a step to check the URL on the running container for a specific status code
      - run:
          name: Check URL
          command: |
            wget -O /tmp/content.txt http://localhost:3000/api/access/settings
            content=$(cat /tmp/content.txt)
            if [[ $content == *EPOCH_DURATION* ]]; then
              echo "EPOCH_DURATION found in the response."
            else
              echo "EPOCH_DURATION not found in the response."
              exit 1
            fi 

      # Add any additional test steps

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build