jobs:
  build:
    docker:
      - image: stromdao/eaf:latest
    working_directory: /app

    steps:
      - checkout

      # Add any steps needed for building your application inside the Docker container

  test:
    docker:
      - image: stromdao/eaf:latest
    working_directory: /app

    steps:
      - checkout

      # Add any steps needed for setting up your application for testing

      - run:
          name: Start Docker container
          command: docker run -d -p 8080:3000 stromdao/eaf:latest

      # Add a step to wait for the container to be fully started (you may need to customize this)
      - run:
          name: Wait for container to start
          command: sleep 30

      # Add a step to check the URL on the running container for a specific status code
      - run:
          name: Check URL
          command: curl -I -s -o /dev/null -w "%{http_code}" http://localhost:8080/api/access/settings

      # Add any additional test steps

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build